# Copyright (c) 2022 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

# SBOM-Composer report for <top level product name>
documentName: "composed-1.0"
# Top Level Composed SBOM product
packageName: "top-level-artifact"
# SPDXRef-composed-sbom-product
spdxID: "SPDXRef-DOCUMENT"
# Should it correspond to composer's version?
packageVersion: "1.0"
# Input from user or NOASSERTION
packageDownloadLocation: ""
filesAnalyzed: false
packageChecksum:
  sha256: "<checksum>"
# License, LicenseRef or NOASSERTION
packageLicenseConcluded: ""
# License, LicenseRef or NOASSERTION
packageLicenseDeclared: ""
# Text or NOASSERTION
packageCopyrightText: ""
# Organization or recognized author of product. Optional
packageSupplier: "Example supplier"
# <text>Any relevant comment</text>. Optional
packageComment: "<text>Example comment</text>"
